### ISSUE TITLE
Error in JSON format and permission denied in log

### ISSUE THREAD

**Issue by aalcaine** [Offerel/roundcube_storage#3]
With the latest version seems there's something wrong with the json formating ("the backend response seems it isn't a json string"):

![captura de pantalla 2018-01-23 a les 7 46 49](https://user-images.githubusercontent.com/32023824/35261849-4c3efab0-0012-11e8-83ee-c794124a440a.png)

Indeed, the log shows an error about permissions, although folder is chmod 777:

```
[23-Jan-2018 06:47:49 UTC] PHP Warning:  mkdir(): S’ha denegat el permís in /usr/share/psa-roundcube/plugins/storage/elfinder/php/connector.roundcube.php on line 17
[23-Jan-2018 06:47:49 UTC] Plugin Storage: Subfolders for $config['storage_basepath'] ($config['storage_folder']) failed. Please check your directory permissions.
```

Folder permissions:

![captura de pantalla 2018-01-23 a les 7 54 05](https://user-images.githubusercontent.com/32023824/35261920-9d7b9118-0012-11e8-9a4e-b78fcb71b3b4.png)

```
drwxr-xr-x  6 root root  4096 21 gen 09:07 .
drwxr-xr-x 44 root root  4096 18 gen 13:23 ..
-rwxr-xr-x  1 root root  1894 22 gen 16:51 client.js
-rwxr-xr-x  1 root root   571 22 gen 16:51 composer.json
-rwxr-xr-x  1 root root   394 21 gen 09:07 config.inc.php
-rwxr-xr-x  1 root root   728 22 gen 16:51 config.inc.php.dist
drwxr-xr-x  8 root root  4096 19 gen 08:05 elfinder
drwxrwxrwx  2 root root  4096 19 gen 08:05 files <-------
-rwxr-xr-x  1 root root 34520 22 gen 16:51 LICENSE
drwxr-xr-x  2 root root  4096 18 gen 12:55 localization
-rwxr-xr-x  1 root root  1996 22 gen 16:51 README.md
drwxr-xr-x  4 root root  4096 18 gen 12:55 skins
-rwxr-xr-x  1 root root  8210 22 gen 16:51 storage.php
```

Storage config contains:

```
// relative path to elfinder
$config['storage_url'] = 'plugins/storage/elfinder/roundcube.html';
// absolute path to internal storage
$config['storage_basepath'] = '/usr/share/psa-roundcube/plugins/storage/files'; <-------
// folder where attachments should saved if requested
$config['storage_attachments'] = 'Adjunts';
// Name of your storage
$config['storage_name'] = 'Els meus fitxers';
```

Paths seem right...

Rgds.

**Comment by Offerel** [comment]
The error message suggests that at least the PHP handler does not have write access to /usr/share/psa-roundcube/plugins/storage/files or the folder to be created. According to your listing, at least /usr/share/psa-roundcube/plugins/storage/files has read/write/execution rights for all, but the owner is root. I assume that root is not the user for PHP or the webserver. The later shouldn't matter if everyone is allowed to write. But 0744 should be enough, if the owner is the user of your PHP handler.

But what I noticed is that you have a $config[' storage_filespath'] variable in your config is missing.

In the message in the error-log I still have the wrong name in the message, but actually $config[' storage_filespath'] is used instead of $config[' storage_folder']. I just corrected the messagetext. 

Please check your config (this seems to be an older variant without this variable) and the permissions of the folders.

**Comment by aalcaine** [comment]
Hi,

Updated the config file with the latest variables, but still appears the error that the backend answer is not JSON.

![captura de pantalla 2018-01-24 a les 12 55 40](https://user-images.githubusercontent.com/32023824/35331002-088cb6dc-0106-11e8-86d1-76bbda4f5ce0.png)

Sorry to "annoy you" with this.

**Comment by Offerel** [comment]
That's strange... Ok, i will not change code this into the next commit, but please try the following:

In connector.roundcube.php please add the line: `error_log($path);` before the line `// elFinder autoload`. Then open a console and watch the roundcube error log file with `tail -f /path/to/your/error_log`. Now, try to open the plugin normally in your browser. This should print out the complete computed root path for the plugin. So you can see, if this is the correct directory. If that's OK, you can comment this line out afterwards with `//` or remove the line. If not, it's not critical but it will print this line out every time, this php file is called.

If it is not the path you have hoped for, you can adjust this path in the config file. I think you will see, where you have to change the correct parts. Normally it should be computed with:

`storage_basepath + roundcube_username + storage_filespath`. The parameter `storage_attachments`, is ony used for saving the attachments and not computed in to the initial call to display the files root.

**Comment by aalcaine** [comment]
I've modified the `connector.roundcube.php` file:

![captura de pantalla 2018-01-24 a les 15 30 37](https://user-images.githubusercontent.com/32023824/35337483-a22cf0c6-011b-11e8-8a53-8599629ae0cc.png)

The javascript console shows nothing, nor any message except the JSON error (but not in the console):

![captura de pantalla 2018-01-24 a les 15 31 56](https://user-images.githubusercontent.com/32023824/35337528-c1fbb658-011b-11e8-8f88-78d96a57be93.png)

The error log shows the following messages:

```
[24-Jan-2018 14:27:34 UTC] PHP Warning:  mkdir(): S’ha denegat el permís in /usr/share/psa-roundcube/plugins/storage/elfinder/php/connector.roundcube.php on line 17
[24-Jan-2018 14:27:34 UTC] Plugin Storage: Subfolders for $config['storage_basepath'] ($config['storage_filespath']) failed. Please check your directory permissions.
```

I've created manually the folders (`plugins/storage/files/user@domain.com/files`) but the same issue persists.

I've tried to use `roundcube_sysuser:roundcube_sysgroup` with 0777 chmod but same issue (the main folder in enigma plugin is owned by `root`, and subfolders and files are created by user `roundcube_sysuser` so I've tried manually to create them).

The current config.php file contains:

```
// relative path to elfinder
$config['storage_url'] = 'plugins/storage/elfinder/roundcube.html';

// The path to the storage is computed as follows: $config['storage_basepath'] + <Rouncube username> + $config['storage_filespath']
// With such a path, every user has it's own folder. The folder $config['storage_filespath'] as subfolder to the users folder
// do let you manage the files better, since you can so save additional things in this userspace.
$config['storage_basepath'] = '/usr/share/psa-roundcube/plugins/storage/files';
$config['storage_filespath'] = '/files';

// folder where attachments should saved if requested
$config['storage_attachments'] = 'Adjunts';

// Name of your storage
$config['storage_name'] = 'Els meus fitxers';
```

If you prefer just tell me what to change instead of uploading a new commit.

**Comment by Offerel** [comment]
The does not print the path in your console, so i don't know the exact path for your config. Your variable `storage_basepath` points to `/usr/share/psa-roundcube/plugins/storage/files` and `storage_filespath` to `/files`. If your username is for example `someone@test.com`, the resulting path is: `/usr/share/psa-roundcube/plugins/storage/files/someone@test.com/files/`. This path is the root for the plugin. If this path does not exist or cant be accessed, you get the above dialog with the json error. If the path  `/usr/share/psa-roundcube/plugins/storage/files/someone@test.com/files/` does not exist, the plugin try's to create it. If this fails, you get the error message in the errorlog of roundcube: `Plugin Storage: Subfolders for $config['storage_basepath'] ($config['storage_filespath']) failed. Please check your directory permissions.`

I cant know, why this path cant be created, but i assume, either the path is wrong or it has not insufficient rights. The path can also be outside the plugin directory, eg. `/mnt/mountpoint/external_hdd/`. If there is a symlink somewhere in the path, this could be a problem, when the system does not allow access or cant follow symlinks. So, please make sure, that there is no symlink involved in the path.

**Comment by Offerel** [comment]
Is your issue solved?

**Comment by aalcaine** [comment]
Problem persists with the latest update (returned not valid JSON). Please, allow me 3-5 days to try it in another server, just to discard that it isn't a permissions problem, as I've tried to chmod with 777, change user from root to apache, roundcubesys, etc, and still the same message.

**Comment by aalcaine** [comment]
Sorry, no solution found:

- Tried to assign manually chmod 777
- Tried to create those folders + assign 777
- Tried to chown to root, roundcube's user, apache and user
- Tried the same without creating the folders
- Tried the same in a different server (with same result :( )

Still appears a message saying that the answer is not a valid JSON.

I'd suggest to debug "in some way" the issue (I can add code if you need it and send you any result).

**Comment by Offerel** [comment]
do you have changed your config, so that the computed folder path is now the correct folder? I assume it should be:

```
$config['storage_basepath'] = '/usr/share/psa-roundcube/plugins/storage/folder_before_username/';
$config['storage_filespath'] = '/folder_after_username/';
```
Both have a trailing slash. Maybe thats the point. I don't know whats your exact paths are, so its not easy to tell you, what you should enter exactly. But you can try to output your computed path, since this is stored in the variable $path. You can output such thing to the error.log with `error.log('text for output'.$somevariable);`

**Comment by Offerel** [comment]
Ahh end please check, if it is really needed, to have this folder under a psa_* folder. Maybe there a problems releated to plesk. Personally, i didn't trust any plesk installation. This is one of the worst written environments I know in my opinion. I've always had problems with Plesk. Frankly, I don't know any system that worked with Plesk without any problems.This is one of the worst written environments I know in my opinion. I've always had problems with Plesk. To be honest, I don't know any system that worked with Plesk without any problems.

**Comment by aalcaine** [comment]
Hi, pending to test, I'll reply asap, probably next Wednesday. I'll install also the plugin in Roundcube installed in Synology NAS, let's try there also :)

**Comment by Offerel** [comment]
To make it a little easier, I just uploaded a new commmit. From this commit on, you can set the `$config[' storage_debug']` switch in `config.inc.php` to **true**. With true, the calculated path is displayed in Roundcube's error. log. If the switch is missing or set to **false**, the path will not be output as before. To show the path the complete new switch is: `$config['storage_debug'] = true;`

**Comment by Offerel** [comment]
Have simplified it a little bit more. In the latest release i have removed the second path variable from the config and put both in $config['storage_basepath']. Use variable %u for the username. The debug mode is also present in this release.

**Comment by aalcaine** [comment]
Found the problem **with the previous commit**. With the Plesk Onyx installation...

The plugin **fails** if the config file includes:

```
$config['storage_basepath'] = '/usr/share/psa-roundcube/plugins/storage/files';
$config['storage_filespath'] = '/files';
```

BUT **WORKS** with:

```
$config['storage_basepath'] = '/usr/share/psa-roundcube/plugins/storage/files**/**';
$config['storage_filespath'] = '/files**/**';
```

This with the last commit (not the last one) which I haven't updated at this time, and I will test in brief. Pending to test with Synology NAS, I'll keep you informed.

**Comment by aalcaine** [comment]
I understand that I can upload and download files from the FILES tab, and I can save attachments there from the reading mail window, but I cannot attach a file stored in the FILES tab directly when composing a new email... I believe this is how it works.

**Comment by Offerel** [comment]
trailing slashes... ok... 

Also with the latest commit, the path should end with a trailing slash...

**Comment by Offerel** [comment]
I will open a new issue with the attach from server issue.

**Comment by aalcaine** [comment]
Bad news: the solution worked before you updated with a new commit.

Now appears the same error (problem with JSON), and in the log:

```
[21-Feb-2018 16:51:15 UTC] PHP Warning:  mkdir(): S’ha denegat el permís in /usr/share/psa-roundcube/plugins/storage/elfinder/php/connector.roundcube.php on line 16
[21-Feb-2018 16:51:15 UTC] Plugin Storage: Trying to create not existing folder specified in $config['storage_basepath'] failed. Please check your directory permissions.
```

Makes no sense, as the "new config" contains the SAME content as the working previous except the new one doesn't have the...
 
`$config['storage_filespath'] = '/files/';`

...variable.

Nor appears the button to attach when composing a new mail, maybe has relation with the plugin "dropbox_attachments", which is enabled. I haven't been able to try it with the last commit as fails loading.

**Comment by Offerel** [comment]
I really don't understand whats going on. I have tested the configuration with different values, so far all paths worked, as long as no symlink was included in the path and the path was closed with a trailing slash. What value do you have in the $config[' storage_basepath'] variable?

I was not aware of a plugin named "dropbox_attachments". But if the "dropbox_attachments" plugin also inserts a button into the "Compose Mail" view, it may of course affect my plugin. My plugin works in such a way that it tries to find the normal attachment button. This only works if this button has the original id and class. If the is found, after this button, my button will be added without changing the old button. If another plugin changes the class, id or the button itself, it cannot be found and my button will not be inserted.

**Comment by aalcaine** [comment]
If I disable the 'dropbox_attachments' the button doesn't appear...

![captura de pantalla 2018-02-22 a les 16 57 53](https://user-images.githubusercontent.com/32023824/36548907-b537468e-17f1-11e8-815d-3b4e1db686f7.png)

... but the plugin works with the previous commit (from 5 days ago, without removing the `$config['storage_filespath'] = '/files/';` variable and adding the parameter for debugging.

Tell me if I can do anything to test.

**Comment by Offerel** [comment]
Internally, nothing is changed with the new version, except that i now replace the %u value with the roundcube username. Since this is now replaced, i didn't need 2 separate values for the path. I have all in one value and change only the username. Before, the path was calculated with $config['storage_basepath'] + username + $config['storage_filespath']. 

I didn't speak your language, so id don't know what the text in your screen means. I can only say, that the plugin works, if it can access the path you configure for writing. If it couldn't access the path for writing, you get the JSON error. Primary, connector.roundcube.php get the path string from the config, replaces %u with the username. After that, there is a check, if the resulting path exists. If not, the file try's to create this directory. If that fails, the plugin stops with a) the JSON Error and b) with the message "Plugin Storage: Trying to create not existing folder specified in $config['storage_basepath'] failed. Please check your directory permissions." in the error.log so that you have a hint, where the problem is.

I have no idea, why your webserver user cant create the directory. In most cases this is a permission problem.

**Comment by aalcaine** [comment]
@Offerel main problem (permissions) is solved. Feel free to close this issue! :)

**Comment by Offerel** [comment]
Great. Many thx for reporting,
